### ISSUE TITLE
Error unknown action: 2 when using non-empty art file

### ISSUE THREAD

**Issue by jshamble** [m1el/mischief-re#2]
When I try to run using a non-empty art file, I get the following error, any ideas why? 
(I'm using the command 
python strokes2svg.py file.art  
python artparser.py file.art  

I can email you the art file if you wish.
)

unknown action: 2
2062619
b'000000000200000019ca854424ca35440000803f00e485441a2687430000803f00000000020000007ffb4a44095035440000803fd6d84c44aace84430000803f000000000200000000c0a94400c01b440000803f00c0a94400c01b440000803f0000000002000000ccf74a443efa35440000803f364d504478a737440000803f0000000002000000983583447a3b38440000803fd89b8544408e36440000803f000000000200000016d98244603038440000803f541151442a8637440000803f0000000002000000'
Traceback (most recent call last):
  File "artparser.py", line 709, in <module>
    sys.exit(main(sys.argv))
  File "artparser.py", line 691, in main
    art = ArtParser(argv[1])
  File "artparser.py", line 626, in __init__
    self.parse_unpacked()
  File "artparser.py", line 678, in parse_unpacked
    (action, pos) = read_action(data, pos)
  File "artparser.py", line 565, in read_action
    die()
NameError: name 'die' is not defined

**Comment by m1el** [comment]
Thank you for reaching out!
Do you mind also telling me which version of Mischief you're using?

This happens because my parser is not complete and doesn't understand everything in the file.
That is unfortunate, but the reality is that I haven't seen all of the "actions" that are stored in the `.art` files.
In your particular case, this is action that is tagged as number two, and has 6 floating values associated with it (e.g. [1070.3156, 727.15845, 1.0, 1071.125, 270.29767, 1.0]), I'm currently not sure what they mean.

I would highly appreciate if you sent me the file you have problems with to m1el.2027@gmail.com
there may be other actions that are unknown to my parser..

**Comment by jshamble** [comment]
Sure thing, I am using Mischeif 2.1.6 (it's the paid version), 
I have sent the file in question to your email address.

My guess is that since it doesn't understand verything, it might have something to do with the imported image files in multiple layers - but this is just a guess.

**Comment by m1el** [comment]
I think I've figured out what was wrong.
The missing actions were: line, polyline, closed polyline, rectangle and ellipse.
`stokes2svg.py` now supports them.

However, I do have to warn you that it doesn't support inserted images or copy/paste layers, so the result may be not as pretty as you may hope. (read: may be unusable for you).

I think the original issue (missing support for polyline/rectangle/ellipse) is now resolved, if you have any other issues, feel free to contact me.
